### ISSUE TITLE
在recylerview中使用Piccaso into(shapeImage)后崩溃

### ISSUE THREAD

**Issue by netdolphin** [AlexMofer/ShapeImageView#1]
如题

**Comment by AlexMofer** [comment]
有没有详细的报错信息？你试试不给其设置Shape看还会不会（不设置，其为普通ImageView）。你这给的信息太少，没法帮你分析。
  
另外  
目前项目已新增[MultifunctionnalImageView](https://github.com/AlexMofer/ProjectX/tree/master/multifunctionalimageview)来替代ShapeImageView，但是ReadMe还没修改。  
后者在实现方案上优于前者，两者的应用上相差无几，具体可参考[ShapeImageViewActivity](https://github.com/AlexMofer/ProjectX/blob/master/app/src/main/java/am/project/x/business/widgets/shapeimageview/ShapeImageViewActivity.java)。  
导入方式：implementation 'am.widget:multifunctionalimageview:1.0.1'
